//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_control_de_labores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSCL_Reporte_Usuario
    {
        public int TN_idReporte { get; set; }
        public Nullable<int> TN_idUsuario { get; set; }
        public Nullable<int> TN_idSubProceso { get; set; }
        public Nullable<System.DateTime> TF_RealizaTarea { get; set; }
        public Nullable<int> TN_Cantidad { get; set; }
    
        public virtual TSCL_Usuario TSCL_Usuario { get; set; }
        public virtual TSCL_SubProceso TSCL_SubProceso { get; set; }
    }
}
