//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_control_de_labores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSCL_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSCL_Usuario()
        {
            this.TSCL_Reporte_Usuario = new HashSet<TSCL_Reporte_Usuario>();
            this.TSCL_SolSubPCol = new HashSet<TSCL_SolSubPCol>();
            this.TSCL_SolSubPCol1 = new HashSet<TSCL_SolSubPCol>();
        }
    
        public int TN_id { get; set; }
        public string TC_Nombre { get; set; }
        public string TC_Apellido { get; set; }
        public int TN_Edad { get; set; }
        public string TC_Tipo_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSCL_Reporte_Usuario> TSCL_Reporte_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSCL_SolSubPCol> TSCL_SolSubPCol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSCL_SolSubPCol> TSCL_SolSubPCol1 { get; set; }
    }
}
