//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_control_de_labores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSCL_SubProceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSCL_SubProceso()
        {
            this.TSCL_Reporte_Usuario = new HashSet<TSCL_Reporte_Usuario>();
            this.TSCL_SolSubPCol = new HashSet<TSCL_SolSubPCol>();
        }
    
        public int TN_idSubProceso { get; set; }
        public Nullable<int> TN_idProceso { get; set; }
        public string TC_Nom_SubProceso { get; set; }
    
        public virtual TSCL_Proceso TSCL_Proceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSCL_Reporte_Usuario> TSCL_Reporte_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSCL_SolSubPCol> TSCL_SolSubPCol { get; set; }
    }
}
